<?php
declare(strict_types=1);

require_once __DIR__ . '/../includes/init.php';
require_login();
require_once __DIR__ . '/../controllers/MaklumatPelajarController.php';

$matrik = trim((string)($_GET['matrik'] ?? ''));
$controller = new MaklumatPelajarController($matrik);
// Profil ialah sambungan kepada Senarai Pelajar, bukan menu berdiri sendiri.
// Kekalkan akses mengikut menu asal supaya pautan Lihat tidak memerlukan menu kedua.
ensure_current_page_access($controller->profile, Database::pdoMysql());
$activeStudentProfileGroup = prestasi_resolve_active_group($controller->profile, Database::pdoMysql());
$canEditStudentProfile = strtoupper(trim((string)($activeStudentProfileGroup['kod'] ?? ''))) !== 'ADM-PE';
if (empty($_SESSION['csrf_token'])) $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
$student = $controller->student;
$PAGE_TITLE = 'Profil Pelajar';
if (!function_exists('h')) { function h(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); } }
function studentValue(?array $student, string $key): string { return trim((string)($student[$key] ?? '')); }
function studentDate(?string $value): string { $value = trim((string)$value); if (preg_match('/^\d{2}\/\d{2}\/\d{4}$/', $value)) return $value; $time = strtotime($value); return $time ? date('d/m/Y', $time) : ''; }
function studentDateInput(?string $value): string { $value = trim((string)$value); if (preg_match('/^(\d{2})\/(\d{2})\/(\d{4})$/', $value, $match)) return $match[3] . '-' . $match[2] . '-' . $match[1]; $time = strtotime($value); return $time ? date('Y-m-d', $time) : ''; }
function studentInitials(string $name): string { $parts = preg_split('/\s+/', trim($name)) ?: []; return strtoupper(implode('', array_map(static fn($part) => substr($part, 0, 1), array_slice($parts, 0, 2)))); }
function studentImageBaseUrl(string $matrik): string { return 'https://kemasukan.upnm.edu.my/tawaran/pelajar/student_image/' . rawurlencode($matrik); }
?>
<!doctype html><html lang="<?= h($controller->lang) ?>"><head>
<?php include __DIR__ . '/../includes/head.php'; ?>
<link rel="stylesheet" href="<?= h(base_url('assets/css/pages/maklumat-pelajar.css')) ?>">
</head><body data-topbar-color="<?= h($_SESSION['theme.topbar'] ?? 'light') ?>" data-menu-color="<?= h($_SESSION['theme.menu'] ?? 'light') ?>" data-layout="vertical" data-sidebar-size="default" class="loading">
<div class="wrapper"><?php include __DIR__ . '/../includes/topbar.php'; ?><?php include __DIR__ . '/../includes/sidebar.php'; ?>
<div class="content-page"><div class="content"><div class="container-fluid">
  <div class="page-title-box"><h4 class="page-title"><i class="ri-user-3-line me-1"></i><?= h($PAGE_TITLE) ?></h4></div>
  <div class="card student-search-card"><div class="card-body"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><h5 class="mb-1">Carian Profil Pelajar</h5><p class="text-muted mb-3">Masukkan nombor matrik untuk memaparkan profil pelajar.</p><form class="d-flex gap-2" method="get"><input class="form-control" style="width:260px" name="matrik" inputmode="numeric" value="<?= h($matrik) ?>" placeholder="No. Matrik"><button class="btn btn-primary" type="submit"><i class="ri-search-line me-1"></i>Cari</button><a class="btn btn-outline-secondary" href="maklumat-pelajar.php">Reset</a></form></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-light" href="senarai-pelajar.php"><i class="ri-arrow-left-line me-1"></i>Kembali ke Senarai Keseluruhan</a><?php if ($matrik !== ''): ?><a class="btn btn-primary" href="cv-pelajar.php?matrik=<?= rawurlencode($matrik) ?>"><i class="ri-file-user-line me-1"></i>Curriculum Vitae Pelajar</a><?php endif; ?></div></div></div></div>
  <?php if ($matrik === ''): ?><div class="alert alert-info">Masukkan nombor matrik untuk memaparkan profil pelajar.</div>
  <?php elseif ($controller->loadError !== null): ?><div class="alert alert-warning"><?= h($controller->loadError) ?></div>
  <?php elseif ($matrik !== '' && !$student): ?><div class="alert alert-info">Rekod pelajar tidak ditemui.</div>
  <?php elseif ($student): ?>
  <?php $name = studentValue($student, 'nama'); $studentImageBase = studentImageBaseUrl(studentValue($student, 'matrik')); $fallbackImage = base_url('assets/images/no-image.jpg'); ?>
<div class="student-top-summary card"><div class="student-cover"><img class="student-photo" src="<?= h($studentImageBase . '.jpg') ?>" data-jpeg="<?= h($studentImageBase . '.jpeg') ?>" data-fallback="<?= h($fallbackImage) ?>" alt="Gambar <?= h($name) ?>"></div><div class="student-summary-card"><div class="student-identity"><h5><?= h($name) ?></h5><p class="student-matric"><i class="ri-id-card-line"></i><?= h(studentValue($student, 'matrik')) ?></p></div><div class="student-study-card"><div class="study-info-grid"><div class="study-info-item"><span><i class="ri-graduation-cap-line"></i>Program Pengajian</span><b><?= h(studentValue($student, 'program_asal') ?: 'Program') ?></b><small><?= h(studentValue($student, 'kod_program') ?: '-') ?></small></div><div class="study-info-item"><span><i class="ri-calendar-2-line"></i>Semester Semasa</span><b><?= h(studentValue($student, 'semester') ?: '-') ?></b><?php if (studentValue($student, 'kod_semester') !== ''): ?><small><?= h(studentValue($student, 'kod_semester')) ?></small><?php endif; ?></div><div class="study-info-item"><span><i class="ri-checkbox-circle-line"></i>Status Pelajar</span><b><?= h(studentValue($student, 'status') ?: '-') ?></b><small class="status-active"><?= h(studentValue($student, 'kategori_status') ?: '-') ?></small></div></div></div></div><nav class="student-top-nav" aria-label="Navigasi maklumat pelajar"><a class="active" href="#peribadi"><i class="ri-user-3-line"></i>Peribadi</a><a href="#pengajian"><i class="ri-graduation-cap-line"></i>Pengajian</a><a href="#perubahan-status"><i class="ri-exchange-line"></i>Status</a><a href="#keputusan-peperiksaan"><i class="ri-file-list-3-line"></i>Peperiksaan</a><a href="#kelayakan-akademik"><i class="ri-graduation-cap-line"></i>Kelayakan</a><a href="#maklumat-penjaga"><i class="ri-heart-3-fill"></i>Penjaga / Waris</a><a href="#rekod-tatatertib"><i class="ri-scales-3-line"></i>Tatatertib</a></nav></div><div class="row g-3">
  <div class="col-xl-9"><div class="card student-profile-card"><div class="card-body"><form id="studentForm" action="../ajax/maklumat-pelajar-update.php" method="post" novalidate data-no-loader><input type="hidden" name="csrf_token" value="<?= h($_SESSION['csrf_token']) ?>"><input type="hidden" name="matrik" value="<?= h(studentValue($student, 'matrik')) ?>">
    <section id="peribadi"><div class="section-heading"><i class="ri-user-3-line"></i><h5>Maklumat Peribadi</h5><?php if ($canEditStudentProfile): ?><button id="editBtn" class="btn btn-primary section-edit-btn" type="button" onclick="document.querySelectorAll('#studentForm input:not([readonly]), #studentForm select:not([data-auto-warga])').forEach(function(field){field.disabled=false;});document.getElementById('saveBar').classList.remove('d-none');this.classList.add('d-none');"><i class="ri-edit-line me-1"></i>Edit</button><?php endif; ?></div><div class="row g-3">
      <?php $fields = [['nama','Nama','text'],['matrik','No. Matrik','text'],['nokp','No. Kad Pengenalan','text'],['tarikh_lahir','Tarikh Lahir','date'],['no_tentera','No. Tentera','text']]; foreach ($fields as [$key,$label,$type]): $readonly = $key === 'matrik'; $value = $key === 'tarikh_lahir' ? studentDateInput(studentValue($student, $key)) : studentValue($student, $key); ?><div class="col-md-6"><label class="form-label"><?= h($label) ?></label><input class="form-control" type="<?= h($type) ?>" name="<?= h($key) ?>" value="<?= h($value) ?>" <?= $readonly ? 'readonly' : 'disabled' ?>></div><?php endforeach; ?>
      <?php $selectedNegeriLahir = studentValue($student, 'kdneglahir') ?: studentValue($student, 'negeri_lahir'); $negeriLahirOptions = $controller->referenceOptions['negeri_lahir'] ?? []; ?><div class="col-md-6"><label class="form-label">Negeri Lahir</label><select class="form-select" name="kdneglahir" disabled><option value="">Pilih Negeri Lahir</option><?php foreach ($negeriLahirOptions as $option): ?><option value="<?= h((string)$option['code']) ?>" <?= (string)$option['code'] === $selectedNegeriLahir ? 'selected' : '' ?>><?= h((string)$option['label']) ?></option><?php endforeach; ?></select></div>
      <?php foreach (['jantina' => ['Jantina', 'kdjantina'], 'bangsa' => ['Bangsa', 'kdbangsa'], 'agama' => ['Agama', 'kdagama'], 'kewarganegaraan' => ['Kewarganegaraan', 'kdkewarganegaraan']] as $key => [$label, $codeKey]): $selected = studentValue($student, $codeKey) ?: studentValue($student, $key); $options = $controller->referenceOptions[$key] ?? []; ?><div class="col-md-6"><label class="form-label"><?= h($label) ?></label><select class="form-select" name="<?= h($codeKey) ?>"<?= $key === 'kewarganegaraan' ? ' id="kewarganegaraan"' : '' ?> disabled><option value="">Pilih <?= h($label) ?></option><?php foreach ($options as $option): ?><option value="<?= h((string)$option['code']) ?>" data-label="<?= h((string)$option['label']) ?>" <?= (string)$option['code'] === $selected ? 'selected' : '' ?>><?= h((string)$option['label']) ?></option><?php endforeach; ?></select></div><?php endforeach; ?>
      <?php $wargaCode = studentValue($student, 'kdwarga'); ?><div class="col-md-6"><label class="form-label">Warganegara</label><select id="wargaSelect" class="form-select" data-auto-warga disabled><option value="">-- Sila Pilih --</option><option value="W" <?= $wargaCode === 'W' ? 'selected' : '' ?>>Warganegara</option><option value="B" <?= $wargaCode === 'B' ? 'selected' : '' ?>>Bukan Warganegara</option></select><input id="kdwarga" type="hidden" name="kdwarga" value="<?= h($wargaCode) ?>"></div>
      <?php foreach ([['oku_no','No. OKU'],['oku_code','Jenis OKU']] as [$key,$label]): ?><div class="col-md-6"><label class="form-label"><?= h($label) ?></label><input class="form-control" name="<?= h($key) ?>" value="<?= h(studentValue($student, $key)) ?>" placeholder="-" disabled></div><?php endforeach; ?>
      <div class="col-12"><div class="profile-divider" aria-hidden="true"></div></div>
      <?php $fields = [['alamat1','Alamat Baris 1'],['alamat2','Alamat Baris 2'],['alamat3','Poskod'],['alamat4','Bandar'],['telefon_rumah','Telefon (Rumah)'],['telefon_hp','Telefon (HP)'],['telefon_terkini','Telefon Terkini'],['email','Emel'],['email_al_fateh','Emel Al Fateh']]; foreach ($fields as [$key,$label]): $inputName = $key === 'telefon_rumah' ? 'telno' : ($key === 'telefon_hp' ? 'hpno' : ($key === 'telefon_terkini' ? 'telno_terkini' : $key)); ?><div class="col-md-6"><label class="form-label"><?= h($label) ?></label><input class="form-control" name="<?= h($inputName) ?>" value="<?= h(studentValue($student, $key)) ?>" disabled></div><?php endforeach; ?>
      <?php $selectedNegeri = studentValue($student, 'kdnegeri') ?: studentValue($student, 'negeri'); $negeriOptions = $controller->referenceOptions['negeri'] ?? []; ?><div class="col-md-6"><label class="form-label">Negeri</label><select class="form-select" name="kdnegeri" disabled><option value="">Pilih Negeri</option><?php foreach ($negeriOptions as $option): ?><option value="<?= h((string)$option['code']) ?>" <?= (string)$option['code'] === $selectedNegeri ? 'selected' : '' ?>><?= h((string)$option['label']) ?></option><?php endforeach; ?></select></div>
    </div></section>
    <section id="pengajian" class="d-none"><div class="section-heading"><i class="ri-graduation-cap-line"></i><h5>Maklumat Pengajian</h5></div><div class="row g-3">
      <?php foreach ([['kod_program','Kod Program'],['program_asal','Program'],['kdfakulti','Kod Fakulti'],['fakulti','Fakulti'],['kdsesimasuk','Kod Sesi Masuk'],['sesi_masuk','Sesi Masuk'],['tahun_pengajian','Tahun Pengajian'],['kdsemsemasa','Kod Semester Semasa'],['semester','Semester Semasa'],['nosem','No. Semester'],['status','Status'],['kategori','Kategori'],['tarikh_daftar','Tarikh Daftar'],['penasihat_akademik','Penasihat Akademik']] as [$key,$label]): ?><div class="col-md-6"><label class="form-label"><?= h($label) ?></label><input class="form-control" value="<?= h($key === 'tarikh_daftar' ? studentDate(studentValue($student, $key)) : studentValue($student, $key)) ?>" readonly></div><?php endforeach; ?>
    </div></section>
    <section id="perubahan-status" class="student-subsection d-none"><div class="section-heading"><i class="ri-exchange-line"></i><h5>Perubahan Status</h5></div>
      <?php $statusTables = [['Status Pelajar', $controller->studentStatusChanges, ['Tarikh', 'Sesi', 'Status', 'Catatan'], static fn(array $row): array => [(string)($row['tarikh'] ?? '-'), (string)($row['sesi'] ?? '-'), trim((string)($row['kod_status'] ?? '') . ' - ' . (string)($row['status'] ?? '')), (string)($row['catatan'] ?? '-')]], ['Status Program', $controller->programStatusChanges, ['Tarikh Kuatkuasa', 'Program Asal', 'Program Baru', 'Catatan'], static fn(array $row): array => [(string)($row['tarikh'] ?? '-'), (string)($row['prog_asal'] ?? '-'), (string)($row['prog_baru'] ?? '-'), (string)($row['catatan'] ?? '-')]], ['Status Kadet', $controller->cadetStatusChanges, ['Tarikh Kuatkuasa', 'Kadet Asal', 'Kadet Baru', 'Catatan'], static fn(array $row): array => [(string)($row['tarikh'] ?? '-'), (string)($row['kadetasal'] ?? '-'), (string)($row['kadetbaru'] ?? '-'), (string)($row['catatan'] ?? '-')]]]; ?>
      <?php foreach ($statusTables as [$title, $records, $headers, $render]): ?><div class="status-table-block"><h6><?= h($title) ?></h6><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th class="text-center" style="width:56px">#</th><?php foreach ($headers as $header): ?><th><?= h($header) ?></th><?php endforeach; ?></tr></thead><tbody><?php if ($records === []): ?><tr><td colspan="<?= h((string)(count($headers) + 1)) ?>" class="text-center text-muted">Tiada Rekod</td></tr><?php else: foreach ($records as $index => $record): ?><tr><td class="text-center"><?= h((string)($index + 1)) ?></td><?php foreach ($render($record) as $cell): ?><td><?= h($cell) ?></td><?php endforeach; ?></tr><?php endforeach; endif; ?></tbody></table></div></div><?php endforeach; ?>
    </section>
    <section id="keputusan-peperiksaan" class="student-subsection d-none"><div class="section-heading"><i class="ri-file-list-3-line"></i><h5>Keputusan Peperiksaan</h5></div>
      <div class="status-table-block"><h6>Markah Peperiksaan</h6><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th class="text-center" style="width:56px">#</th><th>Semester</th><th>Status Akademik</th><th>PNGS</th><th>PNGK</th></tr></thead><tbody><?php if ($controller->examinationResults === []): ?><tr><td colspan="5" class="text-center text-muted">Tiada Rekod</td></tr><?php else: foreach ($controller->examinationResults as $index => $record): ?><tr><td class="text-center"><?= h((string)($index + 1)) ?></td><td><?= h((string)($record['term'] ?? '-')) ?></td><td><?= h(trim((string)($record['kdkelulusan'] ?? '') . ' - ' . (string)($record['kelulusan'] ?? '')) ?: '-') ?></td><td><?= h((string)($record['pngs'] ?? '-')) ?></td><td><?= h((string)($record['pngk'] ?? '-')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
      <div class="status-table-block"><h6>Markah MUET</h6><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th>Band</th></tr></thead><tbody><?php if ($controller->muetResults === []): ?><tr><td class="text-center text-muted">Tiada Rekod</td></tr><?php else: foreach ($controller->muetResults as $record): ?><tr><td><?= h((string)($record['muet'] ?? '-')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
    </section>
    <section id="kelayakan-akademik" class="student-subsection d-none"><div class="section-heading"><i class="ri-graduation-cap-line"></i><h5>Kelayakan Akademik</h5></div>
      <div class="status-table-block"><h6>Keputusan SPM</h6><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th class="text-center" style="width:56px">#</th><th>Kod</th><th>Subjek</th><th>Gred</th></tr></thead><tbody><?php if ($controller->spmResults === []): ?><tr><td colspan="4" class="text-center text-muted">Tiada Rekod</td></tr><?php else: foreach ($controller->spmResults as $index => $record): ?><tr><td class="text-center"><?= h((string)($index + 1)) ?></td><td><?= h((string)($record['kod'] ?? '-')) ?></td><td><?= h((string)($record['subjek'] ?? '-')) ?></td><td><?= h((string)($record['gred'] ?? '-')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
    </section>
    <section id="maklumat-penjaga" class="student-subsection d-none"><div class="section-heading"><i class="ri-heart-3-fill"></i><h5>Maklumat Penjaga / Waris</h5></div>
      <div class="status-table-block"><h6>Maklumat Bapa</h6><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama Bapa</label><input class="form-control" name="nama_bapa" value="<?= h((string)($controller->guardians['nama_bapa'] ?? '')) ?>" disabled></div><div class="col-md-6"><label class="form-label">Telefon Bapa (H/P)</label><input class="form-control" name="telefon_bapa" value="<?= h((string)($controller->guardians['telefon_bapa'] ?? '')) ?>" disabled></div></div></div>
      <div class="status-table-block"><h6>Maklumat Ibu</h6><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama Ibu</label><input class="form-control" name="nama_ibu" value="<?= h((string)($controller->guardians['nama_ibu'] ?? '')) ?>" disabled></div><div class="col-md-6"><label class="form-label">Telefon Ibu (H/P)</label><input class="form-control" name="telefon_ibu" value="<?= h((string)($controller->guardians['telefon_ibu'] ?? '')) ?>" disabled></div></div></div>
    </section>
    <section id="rekod-tatatertib" class="student-subsection d-none"><div class="section-heading"><i class="ri-scales-3-line"></i><h5>Rekod Tatatertib</h5></div><p class="text-muted mb-0">Rekod tatatertib pelajar akan dipaparkan di ruang ini.</p></section>
    <div id="saveBar" class="save-bar d-none"><button class="btn btn-primary" type="submit"><i class="ri-save-line me-1"></i>Simpan Perubahan</button><button id="cancelBtn" class="btn btn-light" type="button" onclick="document.querySelectorAll('#studentForm input:not([readonly])').forEach(function(field){field.value=field.defaultValue;field.disabled=true;});document.querySelectorAll('#studentForm select:not([data-auto-warga])').forEach(function(field){Array.from(field.options).forEach(function(option){option.selected=option.defaultSelected;});field.disabled=true;});document.getElementById('saveBar').classList.add('d-none');document.getElementById('editBtn').classList.remove('d-none');">Batal</button></div>
  </form></div></div></div></div>
  <?php endif; ?>
</div></div><?php include __DIR__ . '/../includes/footer.php'; ?></div></div>
<?php include __DIR__ . '/../includes/script.php'; ?>
<script>window.STUDENT_UPDATE_URL=<?= json_encode(base_url('ajax/maklumat-pelajar-update.php')) ?>; window.STUDENT_CSRF=<?= json_encode($_SESSION['csrf_token']) ?>;</script><script src="<?= h(base_url('assets/js/pages/maklumat-pelajar.js')) ?>?v=<?= h((string)filemtime(__DIR__ . '/../assets/js/pages/maklumat-pelajar.js')) ?>"></script>
</body></html>
