<?php
declare(strict_types=1);

require_once __DIR__ . '/../../../sap/ext/vendor/autoload.php';
require_once __DIR__ . '/../includes/init.php';
require_login();
require_once __DIR__ . '/../controllers/MaklumatPelajarController.php';

use Mpdf\Mpdf;

$matrik = trim((string)($_GET['matrik'] ?? ''));
$controller = new MaklumatPelajarController($matrik);
require_page_access('pages/senarai-pelajar.php', $controller->profile, Database::pdoMysql());
$student = $controller->student;
if (!$student) { http_response_code(404); exit('Rekod pelajar tidak ditemui.'); }
function pdfH(mixed $value): string { $value = mb_strtoupper(trim((string)$value) ?: '-', 'UTF-8'); if (in_array($value, ['MAKLUMAT STATUS PROGRAM', 'REKOD TATATERTIB'], true)) return '<pagebreak />' . $value; return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
function pdfLabel(mixed $value): string { return htmlspecialchars(trim((string)$value) ?: '-', ENT_QUOTES, 'UTF-8'); }
function pdfRows(array $rows): string { $html = ''; foreach ($rows as [$label, $value]) { $isEmail = stripos((string)$label, 'emel') !== false; $display = $isEmail ? htmlspecialchars(mb_strtolower(trim((string)$value) ?: '-', 'UTF-8'), ENT_QUOTES, 'UTF-8') : pdfH($value); $html .= '<tr><th>' . pdfLabel($label) . '</th><td>' . $display . '</td></tr>'; } return $html; }
function pdfGrid(array $items, int $columns = 4): string {
    $rows = []; $current = [];
    foreach ($items as [$label, $value]) {
        $full = in_array($label, ['Alamat', 'Penasihat Akademik'], true);
        if ($full) { if ($current) { $rows[] = $current; $current = []; } $rows[] = [['label' => $label, 'value' => $value, 'full' => true]]; continue; }
        $current[] = ['label' => $label, 'value' => $value, 'full' => false];
        if (count($current) === $columns) { $rows[] = $current; $current = []; }
    }
    if ($current) $rows[] = $current;
    $html = '<table class="info-grid">';
    foreach ($rows as $row) { $html .= '<tr>'; if (($row[0]['full'] ?? false) === true) { $cell = $row[0]; $isEmail = stripos($cell['label'], 'emel') !== false; $display = $isEmail ? htmlspecialchars(mb_strtolower(trim((string)$cell['value']) ?: '-', 'UTF-8'), ENT_QUOTES, 'UTF-8') : pdfH($cell['value']); $html .= '<td colspan="' . $columns . '"><span class="info-label">' . pdfLabel($cell['label']) . '</span><br><strong class="info-value' . ($isEmail ? ' email' : '') . '">' . $display . '</strong></td>'; } else { foreach ($row as $cell) { $isEmail = stripos($cell['label'], 'emel') !== false; $display = $isEmail ? htmlspecialchars(mb_strtolower(trim((string)$cell['value']) ?: '-', 'UTF-8'), ENT_QUOTES, 'UTF-8') : pdfH($cell['value']); $html .= '<td><span class="info-label">' . pdfLabel($cell['label']) . '</span><br><strong class="info-value' . ($isEmail ? ' email' : '') . '">' . $display . '</strong></td>'; } $html .= str_repeat('<td></td>', $columns - count($row)); } $html .= '</tr>'; }
    return $html . '</table>';
}
$address = implode(', ', array_filter([$student['alamat1'] ?? '', $student['alamat2'] ?? '', $student['alamat3'] ?? '', $student['alamat4'] ?? '', $student['negeri'] ?? '']));
$logoFile = __DIR__ . '/../assets/images/logo-upnm.png';
$logo = is_file($logoFile) ? 'data:image/png;base64,' . base64_encode((string)file_get_contents($logoFile)) : '';
$photoUrl = 'https://kemasukan.upnm.edu.my/tawaran/pelajar/student_image/' . rawurlencode((string)($student['matrik'] ?? '')) . '.jpg';
$photoBinary = @file_get_contents($photoUrl);
$photo = is_string($photoBinary) && $photoBinary !== '' ? 'data:image/jpeg;base64,' . base64_encode($photoBinary) : '';
$personal = [
    ['Nama',$student['nama'] ?? ''],['No. Matrik',$student['matrik'] ?? ''],['No. Kad Pengenalan',$student['nokp'] ?? ''],['Tarikh Lahir',$student['tarikh_lahir'] ?? ''],
    ['No. Tentera',$student['no_tentera'] ?? ''],['Jantina',$student['jantina'] ?? ''],['Bangsa',$student['bangsa'] ?? ''],['Agama',$student['agama'] ?? ''],
    ['Negeri Lahir',$student['negeri_lahir'] ?? ''],['Warganegara',$student['warga'] ?? ''],['Kewarganegaraan',$student['kewarganegaraan'] ?? ''],['No. OKU',$student['oku_no'] ?? ''],
    ['Jenis OKU',$student['oku_code'] ?? ''],['Telefon (Rumah)',$student['telefon_rumah'] ?? ''],['Telefon (H/P)',$student['telefon_hp'] ?? ''],['Telefon Terkini',$student['telefon_terkini'] ?? ''],
    ['Alamat',$address],['Emel',$student['email'] ?? ''],['Emel Al Fateh',$student['email_al_fateh'] ?? ''],
];
$study = [['Kod Program',$student['kod_program'] ?? ''],['Program',$student['program_asal'] ?? ''],['Fakulti',$student['fakulti'] ?? ''],['Sesi Masuk',$student['sesi_masuk'] ?? ''],['Semester Semasa',$student['semester'] ?? ''],['Status',$student['status'] ?? ''],['Penasihat Akademik',$student['penasihat_akademik'] ?? '']];
$guardian = [['Nama Bapa',$controller->guardians['nama_bapa'] ?? ''],['Telefon Bapa (H/P)',$controller->guardians['telefon_bapa'] ?? ''],['Nama Ibu',$controller->guardians['nama_ibu'] ?? ''],['Telefon Ibu (H/P)',$controller->guardians['telefon_ibu'] ?? '']];
ob_start(); ?>
<style>body{font-family:dejavusans;color:#1e293b;font-size:9pt}.head{margin:0 0 12px;border-bottom:2px solid #1e3a8a}.head td{border:0;padding:0 0 10px;vertical-align:bottom}.head .logo{width:142px;height:62px;object-fit:contain;object-position:center 65%}.doc-title{font-size:8pt;font-weight:bold;letter-spacing:.08em;color:#1e3a8a}.university{margin-top:2px;font-size:10pt;font-weight:bold;color:#0f172a}.contact{margin-top:4px;font-size:7.5pt;line-height:1.35;color:#526274}.student{text-align:right;padding-right:9px!important}.student-name{font-size:10pt;font-weight:bold;color:#1e293b}.student-matrik{margin-top:3px;font-size:7.5pt;font-weight:bold;color:#64748b}.photo{width:78px;height:78px;object-fit:cover;object-position:center top;border:1px solid #dbe3ec;border-radius:6px;padding:2px}.title{margin-top:11px;padding:6px 9px;border:1px solid #cbd5e1;border-left:5px solid #0f4c81;background:#dbe2ea;color:#1f2937;font-size:9pt;font-weight:bold}.info-grid{width:100%;margin:0;border-collapse:collapse}.info-grid td{width:25%;padding:6px 8px;border:1px solid #e2e8f0;vertical-align:top;background:#fff}.info-grid td:nth-child(even){background:#fafbfd}.info-grid span{display:block;margin-bottom:3px;color:#64748b;font-size:7pt;font-weight:bold;text-transform:uppercase}.info-grid strong{font-size:8pt;font-weight:normal;text-transform:uppercase}.grid{width:100%;margin:0;border-collapse:collapse;font-size:8pt}.grid th,.grid td{padding:6px 7px;border:1px solid #e2e8f0;text-align:left;vertical-align:top}.grid th{background:#f1f5f9;color:#475569;font-size:7pt;text-transform:uppercase}.grid th:first-child,.grid td:first-child{width:25px;text-align:center}.grid tr:nth-child(even){background:#fafbfd}.center{text-align:center}.footer{display:none}</style>
<style>body{font-size:13px}.head{margin:0 0 18px;border-bottom:2px solid #1e3a8a}.head td{padding:0 0 14px;vertical-align:bottom}.head .logo{width:142px;height:90px;object-fit:contain;object-position:center 65%}.doc-title{font-size:11px;line-height:1.15}.university{margin-top:2px;font-size:13px;line-height:1.15}.contact{margin-top:5px;font-size:10px;line-height:1.3}.student{padding-right:12px!important}.student-name{font-size:14px;line-height:1.2}.student-matrik{margin-top:2px;font-size:10px}.photo{width:96px;height:96px;border-radius:8px;padding:3px}.title{margin-top:16px;padding:9px 14px;border-radius:6px 6px 0 0;font-size:13px;letter-spacing:.04em}.info-grid td{padding:9px 10px}.info-grid span{margin-bottom:3px;font-size:10px}.info-grid strong{font-size:11px;line-height:1.45}.grid{font-size:11px}.grid th,.grid td{padding:8px 10px;line-height:1.4}.grid th{font-size:10px}.grid th:first-child,.grid td:first-child{width:44px}</style>
<style>.head .logo{width:140px!important;height:49px!important;max-width:140px!important;max-height:49px!important}.head .university{font-size:10px!important;line-height:1.15!important}.student-name{font-size:10px!important;line-height:1.2!important}.student-matrik{font-size:9px!important}.photo{width:76px!important;height:76px!important}.title{font-size:10px!important;padding:6px 9px!important}.info-grid,.info-grid td,.info-grid .info-label,.info-grid .info-value,.grid,.grid th,.grid td{font-size:10px!important;line-height:1.4!important}.info-grid td{padding:8px 9px}.info-grid .info-label{color:#64748b;font-weight:700;text-transform:none}.info-grid .info-value{color:#1e293b;font-weight:700;text-transform:uppercase}.info-grid .info-value.email{text-transform:none}.grid th,.grid td{padding:8px 9px}</style>
<style>.head{width:100%!important;table-layout:fixed!important}.head td{padding-bottom:7px!important;vertical-align:bottom!important}.head .brand-logo-cell,.head .brand-detail-cell{vertical-align:top!important}.head .student-photo-cell{width:76px!important;padding-right:0!important;text-align:right!important;vertical-align:bottom!important}.head .student-info-row{padding-top:7px!important;text-align:left!important;vertical-align:bottom!important}.grid th:first-child,.grid td:first-child{width:24px!important;min-width:24px!important;max-width:24px!important;padding-left:3px!important;padding-right:3px!important;text-align:center!important}</style>
<table class="head"><tr><td class="brand-logo-cell" style="width:148px"><?php if ($logo): ?><img class="logo" src="<?= $logo ?>" width="140" height="49" style="width:140px;height:49px"><?php endif; ?></td><td class="brand-detail-cell" colspan="2"><div class="doc-title">CURRICULUM VITAE PELAJAR</div><div class="university" style="font-size:10px;line-height:1.15">UNIVERSITI PERTAHANAN NASIONAL MALAYSIA</div><div class="contact">Kem Perdana Sungai Besi, 57000 Kuala Lumpur<br>Telefon: +603-9051 3400 &middot; Emel: ppap@upnm.edu.my</div></td><td class="student-photo-cell" rowspan="2" style="width:76px"><?php if ($photo): ?><img class="photo" src="<?= $photo ?>"><?php endif; ?></td></tr><tr><td class="student-info-row" colspan="3"><span class="student-name"><?= pdfH($student['nama'] ?? '') ?></span>&nbsp;&nbsp;|&nbsp;&nbsp;<span class="student-matrik">NO. MATRIK: <?= pdfH($student['matrik'] ?? '') ?></span></td></tr></table>
<div class="title">MAKLUMAT PERIBADI</div><?= pdfGrid($personal) ?><div class="title">MAKLUMAT PENGAJIAN</div><?= pdfGrid($study, 3) ?><div class="title">MAKLUMAT PENJAGA / WARIS</div><?= pdfGrid($guardian, 4) ?>
<?php foreach ([['MAKLUMAT STATUS PELAJAR',$controller->studentStatusChanges,['Tarikh','Sesi','Status','Catatan'],static fn($r)=>[$r['tarikh']??'-',$r['sesi']??'-',trim(($r['kod_status']??'').' - '.($r['status']??'')),$r['catatan']??'-']],['MAKLUMAT STATUS PROGRAM',$controller->programStatusChanges,['Tarikh','Program Asal','Program Baru','Catatan'],static fn($r)=>[$r['tarikh']??'-',$r['prog_asal']??'-',$r['prog_baru']??'-',$r['catatan']??'-']],['MAKLUMAT STATUS KADET',$controller->cadetStatusChanges,['Tarikh','Kadet Asal','Kadet Baru','Catatan'],static fn($r)=>[$r['tarikh']??'-',$r['kadetasal']??'-',$r['kadetbaru']??'-',$r['catatan']??'-']],['MAKLUMAT PEPERIKSAAN',$controller->examinationResults,['Semester','Status Akademik','PNGS','PNGK'],static fn($r)=>[$r['term']??'-',trim(($r['kdkelulusan']??'').' - '.($r['kelulusan']??'')),$r['pngs']??'-',$r['pngk']??'-']],['KELAYAKAN AKADEMIK',$controller->spmResults,['Kod','Subjek','Gred'],static fn($r)=>[$r['kod']??'-',$r['subjek']??'-',$r['gred']??'-']],['REKOD TATATERTIB',[],['Rekod'],static fn($r)=>[$r['rekod']??'-']]] as [$title,$rows,$heads,$render]): ?><?php if ($rows === []) continue; ?><div class="title"><?= pdfH($title) ?></div><table class="grid"><colgroup><col style="width:24px"><?php foreach($heads as $_): ?><col><?php endforeach; ?></colgroup><tr><th>#</th><?php foreach($heads as $head): ?><th><?= pdfLabel($head) ?></th><?php endforeach; ?></tr><?php foreach($rows as $i=>$row): ?><tr><td><?= $i+1 ?></td><?php foreach($render($row) as $cell): ?><td><?= pdfH($cell) ?></td><?php endforeach; ?></tr><?php endforeach; ?></table><?php endforeach; ?><div class="footer">Laporan ini dijana secara automatik oleh Sistem Akademik Pelajar (SAP).</div>
<?php $html = (string)ob_get_clean(); $html = str_replace(['<div class="title"><pagebreak />MAKLUMAT STATUS PROGRAM</div>', '<div class="title"><pagebreak />REKOD TATATERTIB</div>'], ['<pagebreak /><div class="title">MAKLUMAT STATUS PROGRAM</div>', '<pagebreak /><div class="title">REKOD TATATERTIB</div>'], $html); $html = str_replace('<div class="footer">Laporan ini dijana secara automatik oleh Sistem Akademik Pelajar (SAP).</div>', '', $html); $pdf = new Mpdf(['format' => 'A4','margin_left' => 15,'margin_right' => 15,'margin_top' => 12,'margin_bottom' => 18]); $pdf->SetTitle('Curriculum Vitae Pelajar - ' . (string)($student['matrik'] ?? '')); $pdf->SetHTMLFooter('<div style="border-top:1px solid #d8dee7;padding-top:4px;text-align:right;font-size:7pt;color:#64748b">Laporan ini dijana secara automatik oleh Sistem Akademik Pelajar (SAP) &nbsp;|&nbsp; Halaman {PAGENO}</div>'); $pdf->WriteHTML($html); $pdf->Output('Curriculum_Vitae_Pelajar_' . preg_replace('/\D+/', '', $matrik) . '.pdf', 'I');
